/*
 * This source file was generated by the Gradle 'init' task
 */
package foundation.jdbc;

import foundation.jdbc.repository.EncryptedDatabaseConfig;
import foundation.jdbc.repository.HikariPostgresProjectRepository;
import foundation.jdbc.repository.PostgresDatabaseInitializer;
import foundation.jdbc.repository.ProjectRepository;

/** Starts the PostgreSQL demo using encrypted configuration and a pooled JDBC data source. */
public class App {
    private static final String DEMO_CONFIG_SECRET = "FOUNDATION_DB_CONFIG_SECRET_EXAMPLE_ChangeMe";

    private App() {}

    /**
     * Decrypts configuration, provisions the app database if needed, then checks connectivity.
     *
     * @param args unused command-line arguments
     */
    public static void main(String[] args) {
        String secret = System.getenv("FOUNDATION_DB_CONFIG_SECRET");
        if (secret == null || secret.isBlank()) {
            System.err.println("WARNING: FOUNDATION_DB_CONFIG_SECRET is not set; using the example key. Do not use this fallback outside a demo.");
            secret = DEMO_CONFIG_SECRET;
        }

        EncryptedDatabaseConfig config = EncryptedDatabaseConfig.load("/db-config.yml", secret);
        String adminJdbcUrl = setting("FOUNDATION_DB_ADMIN_URL", config.adminJdbcUrl());
        String jdbcUrl = setting("FOUNDATION_DB_URL", config.jdbcUrl());

        PostgresDatabaseInitializer.ensureDatabaseExists(
                adminJdbcUrl, config.username(), config.password(), config.databaseName());
        try (ProjectRepository repository = new HikariPostgresProjectRepository(
                jdbcUrl, config.username(), config.password())) {
            System.out.printf("Connected to PostgreSQL at %s; found %d project(s).%n",
                    jdbcUrl, repository.findAll().size());
        }
    }

    /** Reads a nonblank environment override, otherwise returns the configured default. */
    private static String setting(String name, String defaultValue) {
        String value = System.getenv(name);
        return value == null || value.isBlank() ? defaultValue : value;
    }
}
