sourceSets {
    main {
        java.srcDirs = ['../app-java17/src/main/java']
        resources.srcDirs = ['../app-java17/src/main/resources']
    }
    test {
        java.srcDirs = ['../app-java17/src/test/java']
        resources.srcDirs = ['../app-java17/src/test/resources']
    }
}

dependencies {
    implementation libs.h2
    implementation libs.sqlite
    implementation libs.hikari
    implementation libs.snakeyaml
    runtimeOnly libs.postgresql
    runtimeOnly libs.slf4j.nop
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'foundation.jdbc.App'
}
