<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.frapee</groupId>
    <artifactId>foundation-maven-template</artifactId>
    <version>1.0-SNAPSHOT</version>
    <relativePath>../foundation-maven-template/pom.xml</relativePath>
  </parent>
  <artifactId>foundation-pojo</artifactId>
  <packaging>pom</packaging>
  <name>Foundation POJO</name>

  <modules>
    <module>foundations-pojo_17</module>
    <module>foundations-pojo_21</module>
    <module>foundations-pojo_25</module>
  </modules>

  <properties>
    <app.mainClass>com.fp.coding.Main</app.mainClass>
  </properties>
</project>
